version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "80:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - app-net


networks:
  app-net:
    driver: bridge
