version: '3.9'
services:
  db:
    image: postgres:15-alpine
    env_file: .env.prod
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  app:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
      target: runtime
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.prod
    ports:
      - "3000:3000"
    networks:
      - app-net

volumes:
  db-data:

networks:
  app-net:
    driver: bridge
