version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile        # étape finale : image Nginx statique
    env_file:
      - .env.prod                   # contient VITE_SUPABASE_URL / KEY, etc.
    ports:
      - "80:3000"                   # host:container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks: [app-net]

networks:
  app-net:
    driver: bridge
