version: '3.9'
services:
  app:
    build:
      context: .
      target: builder
    command: sh -c "pnpm install --frozen-lockfile && pnpm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      VITE_PORT: 3000
    restart: unless-stopped
    depends_on:
      supabase-local:
        condition: service_healthy
    networks:
      - app-network

  supabase-local:
    image: supabase/cli:latest
    command: start
    volumes:
      - ../../.supabase:/home/supabase/.supabase
    ports:
      - "54321:54321"
      - "54322:54322"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "54321"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
