# apps/backend/supabase/config.toml
project_id = "backend"

[api]
enabled = true
port    = 54321
schemas = ["public", "graphql_public"]   # mêmes schémas qu’en prod
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port          = 54322
shadow_port   = 54320
major_version = 17                       # Postgres 17 sur Supabase Cloud :contentReference[oaicite:1]{index=1}

[db.migrations]
enabled       = true
schema_paths  = []                       # vide : on s’appuie sur db pull

[db.seed]
enabled   = true                         # conserve le Seed local facultatif
sql_paths = ["./seed.sql"]

[realtime]  # la garder active pour debug
enabled = true

[studio]
enabled = true
port    = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port    = 54324

[storage]
enabled          = true
file_size_limit  = "50MiB"

[auth]
enabled   = true
site_url  = "http://localhost:3000/"      # valeur cloud :contentReference[oaicite:2]{index=2}
additional_redirect_urls = []             # idem cloud :contentReference[oaicite:3]{index=3}
jwt_expiry                     = 3600
enable_refresh_token_rotation  = true
refresh_token_reuse_interval   = 10
enable_signup                  = true
enable_anonymous_sign_ins      = false

  [auth.email]                  # valeurs cloud
  enable_signup        = true
  double_confirm_changes = true
  enable_confirmations = true
  max_frequency        = "1m0s"
  otp_length           = 6
  otp_expiry           = 600

  [auth.mfa]
  max_enrolled_factors = 10
    [auth.mfa.totp]
    enroll_enabled = true         # activé dans le cloud
    verify_enabled = true

[edge_runtime]
enabled  = true
policy   = "oneshot"              # hot-reload local :contentReference[oaicite:4]{index=4}
inspector_port = 8083
deno_version   = 1

[analytics]
enabled = true
port    = 54327
backend = "postgres"              # par défaut :contentReference[oaicite:5]{index=5}
