project_id = "backend"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000","http://localhost:3000/auth/callback"]
jwt_expiry = 86400
enable_manual_linking = false
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 600

# Exemples pour providers OAuth (facultatif)
#[auth.external.github]
#enabled = true
#client_id = "env(GITHUB_CLIENT_ID)"
#secret = "env(GITHUB_SECRET)"
#redirect_uri = "http://localhost:54321/auth/v1/callback"

[storage]
# Synchronise les buckets distants depuis le cloud
buckets = {}

[functions]
# Si tu utilises des Edge Functions
#search_embeddings = { verify_jwt = false }

[experimental.webhooks]
enabled = true

[db.settings]
track_commit_timestamp = true
